document.write("<header>")
document.write("<div class='logo'>")
document.write("<img src='./imagem/logo02.png'>")
document.write("</div>")
document.write("<nav class='conteinerTopo'>")
document.write("<div class='conteinerTopoDivSuper'>")
document.write("<ul>")
document.write("<li><a href='#'>Home</a></li>")
document.write("<li><a href='#'>Verifica Maior de Idade</a></li>")
document.write("<li><a href='#'>Calcular Média Aluno</a></li>")
document.write("<li><a href='#'>Calcular IMC</a></li>")
document.write("<li><a href='#'>Calcular Aumento</a></li>")
document.write("</ul>")
document.write("</div>")
document.write("</nav>")
document.write("</header>")