document.write("")
document.write("<footer class='footer'>")
document.write("<div class='conteinerFooter'>")
document.write("<p>&copy; 2023 Entra21  Paulo Visbeck</p>")
document.write("</div>")
document.write("</footer>")